import React from 'react';
import "./InteractiveTable.css";
import "bootstrap/dist/css/bootstrap.min.css";
import InteractiveWord from "./InteractiveWord";

const InteractiveTable = props => {
    const { currentWordIndex, currentLessonId } = props;
    return (
        <div className="col-9" id="interactive-table">
            <table className="table" id="table-row" >
                <tbody>
                    <tr>
                        <td id="no-border-left-top-right"></td>
                        <td className="align-middle" id="no-border-left-top-right">0</td>
                        <td className="align-middle" id="no-border-left-top-right">6</td>
                        <td className="align-middle" id="no-border-left-top-right">12</td>
                        <td className="align-middle" id="no-border-left-top-right">18</td>
                        <td className="align-middle" id="no-border-left-top-right">24</td>
                    </tr>
                    <tr>
                        <td className="align-middle" id="no-border-left-top-bottom">30</td>
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={0}
                            underlineMovingVerticallyAfter={0}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={32}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={6}
                            underlineMovingVerticallyAfter={6}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={33}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={12}
                            underlineMovingVerticallyAfter={12}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={34}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={18}
                            underlineMovingVerticallyAfter={18}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={35}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={24}
                            underlineMovingVerticallyAfter={24}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={36}
                            underlineMovingHorizontallyUntil={61}
                        />
                    </tr>
                    <tr>
                        <td className="align-middle" id="no-border-left-top-bottom">35</td>
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={1}
                            underlineMovingVerticallyAfter={1}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={37}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={7}
                            underlineMovingVerticallyAfter={7}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={38}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={13}
                            underlineMovingVerticallyAfter={13}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={39}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={19}
                            underlineMovingVerticallyAfter={19}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={40}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={25}
                            underlineMovingVerticallyAfter={25}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={41}
                            underlineMovingHorizontallyUntil={61}
                        />
                    </tr>
                    <tr>
                        <td className="align-middle" id="no-border-left-top-bottom">40</td>
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={2}
                            underlineMovingVerticallyAfter={2}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={42}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={8}
                            underlineMovingVerticallyAfter={8}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={43}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={14}
                            underlineMovingVerticallyAfter={14}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={44}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={20}
                            underlineMovingVerticallyAfter={20}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={45}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={26}
                            underlineMovingVerticallyAfter={26}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={46}
                            underlineMovingHorizontallyUntil={61}
                        />
                    </tr>
                    <tr>
                        <td className="align-middle" id="no-border-left-top-bottom">45</td>
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={3}
                            underlineMovingVerticallyAfter={3}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={47}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={9}
                            underlineMovingVerticallyAfter={9}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={48}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={15}
                            underlineMovingVerticallyAfter={15}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={49}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={21}
                            underlineMovingVerticallyAfter={21}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={50}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={27}
                            underlineMovingVerticallyAfter={27}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={51}
                            underlineMovingHorizontallyUntil={61}
                        />
                    </tr>
                    <tr>
                        <td className="align-middle" id="no-border-left-top-bottom">50</td>
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={4}
                            underlineMovingVerticallyAfter={4}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={52}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={10}
                            underlineMovingVerticallyAfter={10}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={53}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={16}
                            underlineMovingVerticallyAfter={16}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={54}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={22}
                            underlineMovingVerticallyAfter={22}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={55}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={28}
                            underlineMovingVerticallyAfter={28}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={56}
                            underlineMovingHorizontallyUntil={61}
                        />
                    </tr>
                    <tr>
                        <td className="align-middle" id="no-border-left-top-bottom">55</td>
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={5}
                            underlineMovingVerticallyAfter={5}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={57}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={11}
                            underlineMovingVerticallyAfter={11}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={58}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={17}
                            underlineMovingVerticallyAfter={17}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={59}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={23}
                            underlineMovingVerticallyAfter={23}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={60}
                            underlineMovingHorizontallyUntil={61}
                        />
                        <InteractiveWord
                            currentWordIndex={currentWordIndex}
                            currentLessonId={currentLessonId}
                            wordToDisplayIndex={29}
                            underlineMovingVerticallyAfter={29}
                            underlineMovingVerticallyUntil={30}
                            underlineMovingHorizontallyAt={61}
                            underlineMovingHorizontallyUntil={61}
                        />
                    </tr>
                </tbody>
            </table>
        </div>
    );
}

export default InteractiveTable;