
const lessons = [
    {
        id: 0,
        name: "Pig",
        vocabulary: [
            "fig",
            "big",
            "wig",
            "pig",
            "jig",
            "dig",
            "tip",
            "zip",
            "pip",
            "dip",
            "sip",
            "quip",
            "kid",
            "lid",
            "bid",
            "hid",
            "rid",
            "quid",
            "it",
            "wit",
            "pit",
            "sit",
            "fit",
            "quit",
            "quill",
            "will",
            "fill",
            "hill",
            "sill",
            "bill"
        ]
    },
    {
        id: 1,
        name: "Tub",
        vocabulary: [
            "sun",
            "fun",
            "bun",
            "run",
            "gun",
            "nun",
            "rub",
            "tub",
            "cub",
            "hub",
            "dub",
            "nub",
            "hum",
            "gum",
            "bum",
            "rum",
            "sum",
            "mum",
            "huff",
            "cuff",
            "buff",
            "muff",
            "puff",
            "huff",
            "duck",
            "yuck",
            "buck",
            "luck",
            "puck",
            "muck"
        ]
    },
 
    {
        id: 2,
        name: "Blue Exercise 13",
        vocabulary: [
            "lab",
            "fed",
            "dull",
            "zap",
            "don",
            "tiff",
            "rag",
            "lug",
            "dell",
            "hiss",
            "fad",
            "jog",
            "kin",
            "deck",
            "gab",
            "rib",
            "moss",
            "fuss",
            "cud",
            "miff",
            "lox",
            "jazz",
            "fuzz",
            "pep",
            "vet",
            "pup",
            "peck",
            "toss",
            "fib",
            "nag"
        ]
    },
    {
        id: 3,
        name: "Blue Exercise 15",
        vocabulary: [
            "sham",
            "shack",
            "shad",
            "shall",
            "shell",
            "shed",
            "shock",
            "shot",
            "shod",
            "ship",
            "shin",
            "shut",
            "shuck",
            "shush",
            "hush",
            "mush",
            "rush",
            "rash",
            "mash",
            "bash",
            "cash",
            "lash",
            "dash",
            "dish",
            "wish",
            "fish",
            "josh",
            "gosh",
            "posh"
        ]
    },
    {
        id: 4,
        name: "Blue Exercise 16",
        vocabulary: [
            "chat",
            "chad",
            "chap",
            "chaff",
            "chess",
            "check",
            "chug",
            "chum",
            "chub",
            "chuck",
            "chock",
            "chop",
            "much",
            "such",
            "rich",
            "pitch",
            "ditch",
            "hitch",
            "hatch",
            "batch",
            "catch",
            "latch",
            "fetch",
            "retch",
            "lunch",
            "bunch",
            "punch",
            "pinch",
            "inch"
        ]
    },
    {
        id: 5,
        name: "Blue Exercise 17",
        vocabulary: [
            "thin",
            "thick",
            "Thad",
            "thud",
            "thug",
            "thin",
            "bath",
            "path",
            "hath",
            "math",
            "moth",
            "with",
            "that",
            "than",
            "then",
            "them",
            "thus",
            "this",
            "whiz",
            "whip",
            "whit",
            "whim",
            "whiff",
            "which",
            "when",
            "whet",
            "whop",
            "wham",
            "whack",
            "when"
        ]
    },
    {
        id: 6,
        name: "Blue Exercise 18",
        vocabulary: [
            "rang",
            "bang",
            "sang",
            "Vang",
            "fang",
            "tang",
            "hang",
            "pang",
            "gang",
            "ling",
            "wing",
            "king",
            "sing",
            "wing",
            "ding",
            "Ming",
            "ping",
            "zing",
            "song",
            "long",
            "gong",
            "pong",
            "tong",
            "long",
            "lung",
            "hung",
            "dung",
            "rung",
            "sung",
            "lung"
        ]
    },
    {
        id: 7,
        name: "Blue Exercise 19",
        vocabulary: [
            "shop",
            "shod",
            "shed",
            "mesh",
            "mush",
            "shush",
            "chuck",
            "chum",
            "such",
            "much",
            "match",
            "patch",
            "thud",
            "thug",
            "thin",
            "with",
            "bath",
            "path",
            "when",
            "whet",
            "whack",
            "wham",
            "whiz",
            "which",
            "sang",
            "rang",
            "ring",
            "ding",
            "wing",
            "thing"
        ]
    },
    {
        id: 8,
        name: "Blue Exercise 27",
        vocabulary: [
            "sand",
            "pant",
            "bank",
            "bunk",
            "hunt",
            "fund",
            "west",
            "desk",
            "vest",
            "vast",
            "rasp",
            "task",
            "film",
            "gild",
            "silt",
            "sulk",
            "gulp",
            "gulf",
            "romp",
            "comp",
            "pomp",
            "ramp",
            "damp",
            "camp",
            "next",
            "kept",
            "left",
            "raft",
            "rapt",
            "pact"
        ]
    },
    {
        id: 9,
        name: "Green Exercise 7",
        vocabulary: [
          "fake",
          "gale ",
          "safe",
          "wave",
          "case",
          "rake",
          "late",
          "cape",
          "vase",
          "babe",
          "gaze",
          "glaze",
          "rite",
          "life",
          "wire",
          "vile",
          "lime",
          "slime",
          "tone",
          "rope",
          "hole",
          "robe",
          "hose",
          "chose",
          "fume",
          "cube",
          "muse",
          "rule",
          "rude",
          "nuke",
        ]
    },
  {
        id: 10,
        name: "Green exercise 22",
        vocabulary: [
            "car",
            "cart",
            "mart",
            "carp",
            "harp",
            "sharp",
            "port",
            "fort",
            "tort",
            "torn",
            "corn",
            "scorn",
            "irk",
            "quirk",
            "dirt",
            "sir",
            "fir",
            "first",
            "per",
            "pert",
            "perm",
            "perk",
            "jerk",
            "clerk",
            "furl",
            "curl",
            "hurl",
            "turn",
            "burn",
            "burnt"
        ]
    },
    {
        id: 11,
        name: "Green exercise 24",
        vocabulary: [
            "morn",
            "peel",
            "burp",
            "fold",
            "gut",
            "smart",
            "far",
            "rev",
            "zone",
            "fire",
            "worn",
            "thirst",
            "fuse",
            "low",
            "yak",
            "ark",
            "orb",
            "squirt",
            "herd",
            "team",
            "sigh",
            "hart",
            "sob",
            "forth",
            "tort",
            "ray",
            "mart",
            "quit",
            "gain",
            "burst"
        ]
    },
    {
        id: 12, 
        name: "Green exercise 29",
        vocabulary: [
            "cell",
            "dance",
            "fence",
            "cite",
            "lace",
            "place",
            "gel",
            "gem",
            "hinge",
            "rage",
            "range",
            "grange",
            "knap",
            "knot",
            "knit",
            "knife",
            "knave",
            "knead",
            "wrap",
            "wren",
            "writ",
            "wrote",
            "wreak",
            "wreath",
            "wring",
            "wrong",
            "wroth",
            "gnat",
            "gnu",
            "gnome"
        ]
    },
    {
        id: 13,
        name: "Green Challenge 2",
        vocabulary: [
            "germ",
            "force",
            "gnarl",
            "known",
            "Wright",
            "cinch",
            "farce",
            "dirge",
            "merge",
            "gnat",
            "celt",
            "scent",
            "gorge",
            "knur",
            "urge",
            "wretch",
            "knight",
            "wrench",
            "knob",
            "gnu",
            "cyst",
            "gym",
            "surge",
            "splurge",
            "barge",
            "wry",
            "gee",
            "verge",
            "cede",
            "scene"
        ]
    },
    {
        id: 14,
        name: "Green Exercise 38",
        vocabulary: [
          "wall ",
          "gall",
          "faun",
          "taut",
          "bawl",
          "brawl",
          "now",
          "fowl",
          "gown",
          "loud",
          "gout",
          "grout",
          "join",
          "foil",
          "coif",
          "boy",
          "coy",
          "cloy",
          "hoot",
          "zoom",
          "mood",
          "mew",
          "pew",
          "phew",
          "hook",
          "rook",
          "soot",
          "foot",
          "hood",
          "stood"
        ]
    },
    {
        id: 15,
        name: "Green Exercise 40",
        vocabulary: [
           "crook",
           "shave",
           "flour",
           "wraith",
           "stew",
           "strewn",
           "broach",
           "stood",
           "chase",
           "starch",
           "ounce",
           "flounce",
           "drown",
           "wren",
           "known",
           "screech",
           "valut",
           "flaunt",
           "scrawl",
           "twerp",
           "sluice",
           "gnu",
           "stooge",
           "scrooge",
           "blurt",
           "Joyce",
           "scorch",
           "quirk",
           "choice",
           "spoilt"
        ]
    },
    {
        id: 16,
        name: "Yellow Exercise 5",
        friendlyName: "flap jack  strong man  blast off",
        vocabulary: [
           "slap stick",
           "black list",
           "blast off",
           "wind blast",
           "sun block",
           "step son ",
           "stop gap",
           "skip jack",
           "scab land",
           "drum stick",
           "strong box",
           "chin strap ",
           "bed spring",
           "off spring",
           "scrub land",
           "crab grass",
           "crack pot ",
           "crack up",
           "cross cut",
           "criss cross",
           "frog men",
           "fresh men",
           "press men ",
           "grand son",
           "back drop"
        ]
    },
    {
        id: 17,
        name: "Yellow Exercise 6",
        friendlyName: "bobcat chessman handcuff flapjack",
        vocabulary: [
           "madcap",
           "nitpick",
           "hobnob",
           "henpeck",
           "humbuck",
           "shellfish",
           "chitchat",
           "bathmat",
           "whipstich",
           "singsong",
           "windmill",
           "sandbank",
           "desktop",
           "sunbelt",
           "softback",
           "drumstick",
           "blastoff",
           "grandson",
           "strongbox ",
           "offspring",
           "within",
           "kingpin",
           "checklist",
           "crisscross",
           "sunblock"
        ]
    },
    {
        id: 18,
        name: "Yellow Exercise 8",
        friendlyName: "Yellow Challenge",
        vocabulary: [
           "upset",
           "hatbox",
           "standoff",
           "cropland",
           "hamstring",
           "slipshod",
           "handprint",
           "sandblast",
           "fishpond",
           "backlash",
           "handbell",
           "granddad",
           "potluck",
           "checklist",
           "muskrat",
           "sandhill",
           "pickax",
           "quicksand",
           "shamrock",
           "sundress",
           "frostnip",
           "matchbox",
           "backflip",
           "lipstick",
           "sunstruck"
        ]
    },
    {
        id: 19,
        name: "Yellow Exercise 15",
        friendlyName: "foot stool  news boy  oil can",
        vocabulary: [
           "foot print",
           "foot fault",
           "fish hook",
           "push cart",
           "sour puss",
           "proof read",
           "fool proof",
           "school room",
           "whisk broom",
           "foot stool",
           "news stand",
           "new born",
           "dew drop",
           "screw ball",
           "cork screw",
           "joy ride ",
           "kill joy",
           "high boy",
           "cow boy",
           "plow boy",
           "oil cloth",
           "oil skin",
           "top soil",
           "gum boil",
           "check point"
        ]
    }
];

export function getword(lessonId, wordIndex) {
    return lessons[lessonId].vocabulary[wordIndex];
}

export function getLessonName(lessonId) {
    return lessons[lessonId].name;
}
