
const lessons = [
    {
        id: 0,
        name: "Pig",
        vocabulary: [
            "fig",
            "big",
            "wig",
            "pig",
            "jig",
            "dig",
            "tip",
            "zip",
            "pip",
            "dip",
            "sip",
            "quip",
            "kid",
            "lid",
            "bid",
            "hid",
            "rid",
            "quid",
            "it",
            "wit",
            "pit",
            "sit",
            "fit",
            "quit",
            "quill",
            "will",
            "fill",
            "hill",
            "sill",
            "bill"
        ]
    },
    {
        id: 1,
        name: "Tub",
        vocabulary: [
            "sun",
            "fun",
            "bun",
            "run",
            "gun",
            "nun",
            "rub",
            "tub",
            "cub",
            "hub",
            "dub",
            "nub",
            "hum",
            "gum",
            "bum",
            "rum",
            "sum",
            "mum",
            "huff",
            "cuff",
            "buff",
            "muff",
            "puff",
            "huff",
            "duck",
            "yuck",
            "buck",
            "luck",
            "puck",
            "muck"
        ]
    },
    {
        id: 2,
        name: "Green Review 1",
        vocabulary: [
            "car",
            "cart",
            "mart",
            "carp",
            "harp",
            "sharp",
            "port",
            "fort",
            "tort",
            "torn",
            "corn",
            "scorn",
            "irk",
            "quirk",
            "dirt",
            "sir",
            "fir",
            "first",
            "per",
            "pert",
            "perm",
            "perk",
            "jerk",
            "clerk",
            "furl",
            "curl",
            "hurl",
            "turn",
            "burn",
            "burnt"
        ]
    },
    {
        id: 3,
        name: "Green Challenge 1",
        vocabulary: [
            "morn",
            "peel",
            "burp",
            "fold",
            "gut",
            "smart",
            "far",
            "rev",
            "zone",
            "fire",
            "worn",
            "thirst",
            "fuse",
            "low",
            "yak",
            "ark",
            "orb",
            "squirt",
            "herd",
            "team",
            "sigh",
            "hart",
            "sob",
            "forth",
            "tort",
            "ray",
            "mart",
            "quit",
            "gain",
            "burst"
        ]
    },
    {
        id: 4,
        name: "Green Review 2",
        vocabulary: [
            "cell",
            "dance",
            "fence",
            "cite",
            "lace",
            "place",
            "gel",
            "gem",
            "hinge",
            "rage",
            "range",
            "grange",
            "knap",
            "knot",
            "knit",
            "knife",
            "knave",
            "knead",
            "wrap",
            "wren",
            "writ",
            "wrote",
            "wreak",
            "wreath",
            "wring",
            "wrong",
            "wroth",
            "gnat",
            "gnu",
            "gnome"
        ]
    },
    {
        id: 5,
        name: "Green Challenge 2",
        vocabulary: [
            "germ",
            "force",
            "gnarl",
            "known",
            "Wright",
            "cinch",
            "farce",
            "dirge",
            "merge",
            "gnat",
            "celt",
            "scent",
            "gorge",
            "knur",
            "urge",
            "wretch",
            "knight",
            "wrench",
            "knob",
            "gnu",
            "cyst",
            "gym",
            "surge",
            "splurge",
            "barge",
            "wry",
            "gee",
            "verge",
            "cede",
            "scene"
        ]
    },
    {
        id: 6,
        name: "Blue Exercise 13",
        vocabulary: [
            "lab",
            "fed",
            "dull",
            "zap",
            "don",
            "tiff",
            "rag",
            "lug",
            "dell",
            "hiss",
            "fad",
            "jog",
            "kin",
            "deck",
            "gab",
            "rib",
            "moss",
            "fuss",
            "cud",
            "miff",
            "lox",
            "jazz",
            "fuzz",
            "pep",
            "vet",
            "pup",
            "peck",
            "toss",
            "fib",
            "nag"
        ]
    },
    {
        id: 7,
        name: "Blue Exercise 15",
        vocabulary: [
            "sham",
            "shack",
            "shad",
            "shall",
            "shell",
            "shed",
            "shock",
            "shot",
            "shod",
            "ship",
            "shin",
            "shut",
            "shuck",
            "shush",
            "hush",
            "mush",
            "rush",
            "rash",
            "mash",
            "bash",
            "cash",
            "lash",
            "dash",
            "dish",
            "wish",
            "fish",
            "josh",
            "gosh",
            "posh"
        ]
    },
    {
        id: 8,
        name: "Blue Exercise 16",
        vocabulary: [
            "chat",
            "chad",
            "chap",
            "chaff",
            "chess",
            "check",
            "chug",
            "chum",
            "chub",
            "chuck",
            "chock",
            "chop",
            "much",
            "such",
            "rich",
            "pitch",
            "ditch",
            "hitch",
            "hatch",
            "batch",
            "catch",
            "latch",
            "fetch",
            "retch",
            "lunch",
            "bunch",
            "punch",
            "pinch",
            "inch"
        ]
    },
    {
        id: 9,
        name: "Blue Exercise 17",
        vocabulary: [
            "thin",
            "thick",
            "Thad",
            "thud",
            "thug",
            "thin",
            "bath",
            "path",
            "hath",
            "math",
            "moth",
            "with",
            "that",
            "than",
            "then",
            "them",
            "thus",
            "this",
            "whiz",
            "whip",
            "whit",
            "whim",
            "whiff",
            "which",
            "when",
            "whet",
            "whop",
            "wham",
            "whack",
            "when"
        ]
    },
    {
        id: 10,
        name: "Blue Exercise 18",
        vocabulary: [
            "rang",
            "bang",
            "sang",
            "Vang",
            "fang",
            "tang",
            "hang",
            "pang",
            "gang",
            "ling",
            "wing",
            "king",
            "sing",
            "wing",
            "ding",
            "Ming",
            "ping",
            "zing",
            "song",
            "long",
            "gong",
            "pong",
            "tong",
            "long",
            "lung",
            "hung",
            "dung",
            "rung",
            "sung",
            "lung"
        ]
    },
    {
        id: 11,
        name: "Blue Exercise 19",
        vocabulary: [
            "shop",
            "shod",
            "shed",
            "mesh",
            "mush",
            "shush",
            "chuck",
            "chum",
            "such",
            "much",
            "match",
            "patch",
            "thud",
            "thug",
            "thin",
            "with",
            "bath",
            "path",
            "when",
            "whet",
            "whack",
            "wham",
            "whiz",
            "which",
            "sang",
            "rang",
            "ring",
            "ding",
            "wing",
            "thing"
        ]
    },
    {
        id: 12,
        name: "Blue Exercise 27",
        vocabulary: [
            "sand",
            "pant",
            "bank",
            "bunk",
            "hunt",
            "fund",
            "west",
            "desk",
            "vest",
            "vast",
            "rasp",
            "task",
            "film",
            "gild",
            "silt",
            "sulk",
            "gulp",
            "gulf",
            "romp",
            "comp",
            "pomp",
            "ramp",
            "damp",
            "camp",
            "next",
            "kept",
            "left",
            "raft",
            "rapt",
            "pact"
        ]
    },
    {
        id: 13,
        name: ""
    }

];

export function getword(lessonId, wordIndex) {
    return lessons[lessonId].vocabulary[wordIndex];
}

export function getLessonName(lessonId) {
    return lessons[lessonId].name;
}
